services:
  db:
    image: postgres:17
    container_name: manga-translator-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - manga-translator_default

  pgadmin:
    image: dpage/pgadmin4
    container_name: manga-translator-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 43200
      PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME: 43200
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - manga-translator_default
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  web:
    build: .
    container_name: manga-translator-web
    command: >
      bash -c "uv venv &&
      uv pip install . &&
      uv pip install --group dev &&
      source .venv/bin/activate &&
      uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    volumes:
      - .:/myapp
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    networks:
      - manga-translator_default

  minio:
    image: minio/minio
    container_name: manga-translator-minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    entrypoint: sh
    volumes:
      - minio-volume:/data
    command: -c "minio server /data --address :9000 --console-address :9090;"
    networks:
      - manga-translator_default

  redis:
    image: redis:7.4.2
    container_name: manga-translator-redis
    ports:
      - "6379:6379"
    networks:
      - manga-translator_default

volumes:
  postgres_data:
  minio-volume:
  pgadmin-data:

networks:
  manga-translator_default:
    external: true
