services:
  db:
    image: postgres:15
    container_name: service-base-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - service-base_default

  web:
    build: .
    container_name: service-base-web
    command: >
      bash -c "uv venv &&
      uv pip install . &&
      uv pip install --group dev &&
      source .venv/bin/activate &&
      uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    volumes:
      - .:/myapp
    ports:
      - "8000:8000" # for fastapi
      - "8888:8888" # for jupyter notebook when debugging
    depends_on:
      - db
    networks:
      - service-base_default

  sendria:
    image: msztolcman/sendria:v2.2.2.0
    container_name: service-base-sendria
    ports:
      - "1025:1025" # SMTP
      - "1080:1080" # Web UI
    networks:
      - service-base_default

volumes:
  postgres_data:
  pgadmin-data:

networks:
  service-base_default:
    external: true
