"""add wallet

Revision ID: 0aa4e1912fc4
Revises: 7d027468cc23
Create Date: 2025-05-26 14:07:50.773431

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "0aa4e1912fc4"
down_revision: Union[str, None] = "7d027468cc23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("stripe_customer_id", sa.String(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wallets_stripe_customer_id"),
        "wallets",
        ["stripe_customer_id"],
        unique=True,
    )
    op.create_table(
        "wallet_transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("stripe_payment_intent_id", sa.String(), nullable=True),
        sa.Column(
            "wallet_transaction_type",
            sa.Enum("DEPOSIT", "SPEND", name="wallettransactiontype"),
            nullable=False,
        ),
        sa.Column(
            "wallet_transaction_status",
            sa.Enum("PENDING", "COMPLETED", "FAILED", name="wallettransactionstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wallet_transactions_stripe_payment_intent_id"),
        "wallet_transactions",
        ["stripe_payment_intent_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wallet_transactions_stripe_payment_intent_id"),
        table_name="wallet_transactions",
    )
    op.drop_table("wallet_transactions")
    op.drop_index(op.f("ix_wallets_stripe_customer_id"), table_name="wallets")
    op.drop_table("wallets")
    # ### end Alembic commands ###
