"""add

Revision ID: 11061b015f0b
Revises: d6ac0dc942f6
Create Date: 2025-06-26 10:31:43.505271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11061b015f0b'
down_revision: Union[str, None] = 'd6ac0dc942f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('tax_type', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('tax_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'tax_id')
    op.drop_column('organizations', 'tax_type')
    # ### end Alembic commands ###
