"""add unique

Revision ID: 16b9f2150993
Revises: 86562ed4b8f4
Create Date: 2025-04-28 01:22:30.444073

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '16b9f2150993'
down_revision: Union[str, None] = '86562ed4b8f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_character_images_display_id', table_name='character_images')
    op.create_index(op.f('ix_character_images_display_id'), 'character_images', ['display_id'], unique=True)
    op.drop_index('ix_characters_display_id', table_name='characters')
    op.create_index(op.f('ix_characters_display_id'), 'characters', ['display_id'], unique=True)
    op.drop_index('ix_episodes_display_id', table_name='episodes')
    op.create_index(op.f('ix_episodes_display_id'), 'episodes', ['display_id'], unique=True)
    op.drop_index('ix_pages_display_id', table_name='pages')
    op.create_index(op.f('ix_pages_display_id'), 'pages', ['display_id'], unique=True)
    op.drop_index('ix_products_display_id', table_name='products')
    op.create_index(op.f('ix_products_display_id'), 'products', ['display_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_display_id'), table_name='products')
    op.create_index('ix_products_display_id', 'products', ['display_id'], unique=False)
    op.drop_index(op.f('ix_pages_display_id'), table_name='pages')
    op.create_index('ix_pages_display_id', 'pages', ['display_id'], unique=False)
    op.drop_index(op.f('ix_episodes_display_id'), table_name='episodes')
    op.create_index('ix_episodes_display_id', 'episodes', ['display_id'], unique=False)
    op.drop_index(op.f('ix_characters_display_id'), table_name='characters')
    op.create_index('ix_characters_display_id', 'characters', ['display_id'], unique=False)
    op.drop_index(op.f('ix_character_images_display_id'), table_name='character_images')
    op.create_index('ix_character_images_display_id', 'character_images', ['display_id'], unique=False)
    # ### end Alembic commands ###
