"""add asigned

Revision ID: 277a81e9f45b
Revises: d346b7d09ec6
Create Date: 2025-06-24 10:43:45.612262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '277a81e9f45b'
down_revision: Union[str, None] = 'd346b7d09ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_organization_invitations', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('user_organization_invitations', 'completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_organization_invitations', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('user_organization_invitations', 'assigned_at')
    # ### end Alembic commands ###
