"""add deleted_at

Revision ID: 29ee383b290c
Revises: ad4b913e75ba
Create Date: 2025-06-24 03:34:16.077086

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29ee383b290c"
down_revision: Union[str, None] = "ad4b913e75ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_organization_assignments",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_organization_assignments", "deleted_at")
    # ### end Alembic commands ###
