"""remove

Revision ID: 4a61d02faa89
Revises: 5e82ae03cc5a
Create Date: 2025-06-24 14:02:33.749079

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4a61d02faa89"
down_revision: Union[str, None] = "5e82ae03cc5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_organization_invitations", "assigned_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_organization_invitations",
        sa.Column(
            "assigned_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
