"""add user api key

Revision ID: 57170b11d50c
Revises: 0aa4e1912fc4
Create Date: 2025-06-02 03:22:18.552171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57170b11d50c'
down_revision: Union[str, None] = '0aa4e1912fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('allowed_origin', sa.String(), nullable=True),
    sa.Column('allowed_ip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_api_keys_api_key'), 'user_api_keys', ['api_key'], unique=True)
    op.create_index(op.f('ix_user_api_keys_id'), 'user_api_keys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_keys_id'), table_name='user_api_keys')
    op.drop_index(op.f('ix_user_api_keys_api_key'), table_name='user_api_keys')
    op.drop_table('user_api_keys')
    # ### end Alembic commands ###
