"""add storage key

Revision ID: 672090702e56
Revises: e46fc1a8e8fd
Create Date: 2025-05-03 00:44:57.401373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672090702e56'
down_revision: Union[str, None] = 'e46fc1a8e8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_images', sa.Column('storage_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_images', 'storage_key')
    # ### end Alembic commands ###
