"""add deleted_at

Revision ID: 7438b810b5fe
Revises: a641cee557ec
Create Date: 2025-04-22 04:30:54.935600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7438b810b5fe'
down_revision: Union[str, None] = 'a641cee557ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_images', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('characters', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('episodes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('products', 'deleted_at')
    op.drop_column('pages', 'deleted_at')
    op.drop_column('episodes', 'deleted_at')
    op.drop_column('characters', 'deleted_at')
    op.drop_column('character_images', 'deleted_at')
    # ### end Alembic commands ###
