"""add with tax

Revision ID: 78b95c1aad7a
Revises: 7ade37bc1072
Create Date: 2025-06-26 06:13:19.572765

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78b95c1aad7a"
down_revision: Union[str, None] = "7ade37bc1072"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_wallet_transactions",
        sa.Column(
            "amount_inclusive_tax",
            sa.Numeric(precision=38, scale=9, decimal_return_scale=True),
            nullable=True,
        ),
    )
    op.add_column(
        "user_wallet_transactions",
        sa.Column(
            "amount_inclusive_tax",
            sa.Numeric(precision=38, scale=9, decimal_return_scale=True),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_wallet_transactions", "amount_inclusive_tax")
    op.drop_column("organization_wallet_transactions", "amount_inclusive_tax")
    # ### end Alembic commands ###
