"""change image key

Revision ID: 86562ed4b8f4
Revises: 7b1aaa04a92d
Create Date: 2025-04-28 00:30:06.213489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86562ed4b8f4'
down_revision: Union[str, None] = '7b1aaa04a92d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_images', sa.Column('image_storage_key', sa.String(length=255), nullable=False))
    op.drop_column('character_images', 'image_url')
    op.add_column('pages', sa.Column('before_changed_image_storage_key', sa.String(length=255), nullable=False))
    op.add_column('pages', sa.Column('after_changed_image_storage_key', sa.String(length=255), nullable=False))
    op.drop_column('pages', 'before_changed_image_url')
    op.drop_column('pages', 'after_changed_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('after_changed_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('pages', sa.Column('before_changed_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('pages', 'after_changed_image_storage_key')
    op.drop_column('pages', 'before_changed_image_storage_key')
    op.add_column('character_images', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('character_images', 'image_storage_key')
    # ### end Alembic commands ###
