"""add balance_after_transaction

Revision ID: 8b73c10a234f
Revises: d99da5e18007
Create Date: 2025-06-21 05:15:59.369099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b73c10a234f'
down_revision: Union[str, None] = 'd99da5e18007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_wallet_transactions', sa.Column('balance_after_transaction', sa.Numeric(precision=38, scale=9, decimal_return_scale=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_wallet_transactions', 'balance_after_transaction')
    # ### end Alembic commands ###
