"""remove storage key

Revision ID: c9549d7d61f8
Revises: 16b9f2150993
Create Date: 2025-04-28 01:36:00.191167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9549d7d61f8'
down_revision: Union[str, None] = '16b9f2150993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_images', 'image_storage_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_images', sa.Column('image_storage_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
