"""change to numeric

Revision ID: f434dbd651bb
Revises: 434696e40125
Create Date: 2025-06-20 10:35:26.584972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f434dbd651bb'
down_revision: Union[str, None] = '434696e40125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_wallet_transactions', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=38, scale=9),
               existing_nullable=False)
    op.alter_column('user_wallets', 'balance',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=38, scale=9),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_wallets', 'balance',
               existing_type=sa.Numeric(precision=38, scale=9),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_wallet_transactions', 'amount',
               existing_type=sa.Numeric(precision=38, scale=9),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
