"""add

Revision ID: ff56375216d5
Revises: 085693a0f8ac
Create Date: 2025-06-26 10:05:17.500717

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ff56375216d5"
down_revision: Union[str, None] = "085693a0f8ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("user_wallet_transactions_user_wallet_id_fkey"),
        "user_wallet_transactions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "user_wallet_transactions",
        "user_wallets",
        ["user_wallet_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("user_wallets_user_id_fkey"), "user_wallets", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "user_wallets", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_wallets", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_wallets_user_id_fkey"), "user_wallets", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "user_wallet_transactions", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_wallet_transactions_user_wallet_id_fkey"),
        "user_wallet_transactions",
        "user_wallets",
        ["user_wallet_id"],
        ["id"],
    )
    # ### end Alembic commands ###
