apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: fastapi-managed-cert
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: gce
  rules:
    - host: service-base-auth.baltoon.jp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi-service
                port:
                  number: 80
