apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi
  namespace: production
  annotations:
    iam.gke.io/gcp-service-account: "service-base-deployment-user@aiproject-460606.iam.gserviceaccount.com"
