name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main, develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      # (1) Terraform を使ってインフラを最新化（クラスタ・SQLなど）
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Plan
        run: terraform -chdir=./infra plan \
          -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var "db_password=${{ secrets.DB_PASSWORD }}"

      - name: Terraform Apply
        run: terraform -chdir=./infra apply -auto-approve \
          -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var "db_password=${{ secrets.DB_PASSWORD }}"

      # (2) Dockerイメージをビルド & Push
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="takahashiseiya/service-base-fastapi-web"
          COMMIT_SHA="${{ github.sha }}"
          SHORT_SHA=$(echo "$COMMIT_SHA" | cut -c1-7)

          docker build -t $IMAGE_NAME:$SHORT_SHA -f Dockerfile .
          docker push $IMAGE_NAME:$SHORT_SHA
          docker tag $IMAGE_NAME:$SHORT_SHA $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
