name: CI

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/ci.yml"
      - "manga_translator/**"
      - "test/**"
      - "requirements.txt"
      - "requirements-dev.txt"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/ci.yml"
      - "manga_translator/**"
      - "test/**"
      - "requirements.txt"
      - "requirements-dev.txt"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"] # Add more Python versions if needed
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt -r requirements-dev.txt
      - name: Test
        run: |
          source .venv/bin/activate
          pytest test
        timeout-minutes: 5
      - name: Lint *.py files
        run: |
          source .venv/bin/activate
          pylint $(git ls-files '*.py')
        if: always()
        continue-on-error: true # to not fail CI on lint errors
