name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      minio:
        image: minio/minio
        env:
          MINIO_ROOT_USER: admin
          MINIO_ROOT_PASSWORD: password
        ports:
          - 9000:9000
          - 9090:9090
        options: >-
          --entrypoint /bin/sh
          -c "minio server /data --console-address :9090"

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl g++ wget ffmpeg libsm6 libxext6 gimp libvulkan1 cargo libpq-dev
          # (省略) ここ以降はすでにある手順
          curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="$HOME/.local/bin" sh
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          uv python install 3.10.16
          uv venv
          uv pip install .
          uv pip install --group dev

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 1
          done

      - name: Execute init.sql
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -f ./docker/init.sql

      - name: Load .env.ci
        run: |
          cp .env.ci .env.test

      - name: Run database migrations
        run: |
          ls -la
          echo "Running migrations..."
          source .venv/bin/activate
          ENV=test alembic upgrade head

      - name: Wait for MinIO to be ready
        run: |
          until [ "$(curl -s -o /dev/null -w ''%{http_code}'' http://127.0.0.1:9000/minio/health/live)" = "200" ]; do
            echo "Waiting for minio..."
            sleep 1
          done
          echo "MinIO is ready!"

      - name: Setup MinIO buckets
        run: |
          # mc (minio client) は Docker から単発で呼び出す例
          # ※ もしローカルにインストール済なら適宜変更してください
          docker run --network host --entrypoint sh --rm minio/mc -c "
            mc alias set local http://127.0.0.1:9000 admin password &&
            mc mb local/manga-translator-dev &&
            mc mb local/manga-translator-test
          "

      - name: Test with coverage
        run: |
          source .venv/bin/activate
          pytest --cov=app --cov-report=term-missing --cov-report=html
        timeout-minutes: 5

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

      - name: Lint *.py files
        if: always()
        continue-on-error: true
        run: |
          source .venv/bin/activate
          pylint $(git ls-files '*.py')

      - name: Ruff *.py files
        if: always()
        continue-on-error: true
        run: |
          source .venv/bin/activate
          ruff check .

      - name: mypy
        if: always()
        continue-on-error: true
        run: |
          source .venv/bin/activate
          mypy --config-file mypy.ini .
