name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl g++ wget ffmpeg libsm6 libxext6 gimp libvulkan1 cargo libpq-dev
          curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="$HOME/.local/bin" sh
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          uv python install 3.10.16
          uv venv
          uv pip install .
          uv pip install --group dev

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 1
          done
      - name: Execute init.sql
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -f ./docker/init.sql
      - name: Load .env.ci
        run: |
          cp .env.ci .env.test
      - name: Run database migrations
        run: |
          ls -la
          echo "Running migrations..."
          source .venv/bin/activate
          ENV=test alembic upgrade head
      - name: Test with coverage
        run: |
          source .venv/bin/activate
          pytest --cov=app --cov-report=term-missing --cov-report=html
          timeout-minutes: 5
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
      - name: Generate coverage summary
        run: |
          source .venv/bin/activate
          coverage report > coverage.txt

      - name: Comment coverage report on PR
        if: github.event_name == 'pull_request'
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GIT_HUB_TOKEN }}
          title: Coverage Report
          body: |
            ## Coverage Report
            \`\`\`
            $(cat coverage.txt)
            \`\`\`
      - name: Lint *.py files
        run: |
          source .venv/bin/activate
          pylint $(git ls-files '*.py')
        if: always()
        continue-on-error: true # to not fail CI on lint errors
      - name: Ruff *.py files
        run: |
          source .venv/bin/activate
          ruff check .
        if: always()
        continue-on-error: true # to not fail CI on lint errors
      - name: mypy
        run: |
          source .venv/bin/activate
          mypy .
        if: always()
        continue-on-error: true # to not fail CI on lint errors
